version: '3.8'
services:
  php:
    container_name: snakegame
    image: php:latest
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:80"
  db:
    container_name: snakedb
    command: --default-authentication-plugin=mysql_native_password
    build:
      context: ./database
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3306:3306"